apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-guide-deployment
spec:
  selector:
    matchLabels:
      app: kubernetes-guide-pod
  template:
    metadata:
      labels:
        app: kubernetes-guide-pod
    spec:
      containers:
      - name: kubernetes-guide-container
        image: 066851930357/kubernetes-guide:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
